### ISSUE TITLE
Your deployment is down

### ISSUE THREAD

**Issue by piplup7575** [JeffreyWangDev/githubProfileJudge#1]
I can't check out your demo, it doesn't seem to be working at the moment.

![image](https://github.com/user-attachments/assets/789c0a43-5ac0-4840-8984-4c1544273a12)

**Comment by piplup7575** [comment]
Seems to be back up now

**Comment by JeffreyWangDev** [comment]
I needed to change the url, they are all here!
https://autodeploy.jeffrey.hackclub.app/
